apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smesh-podmonitor
  namespace: openshift-gitops
  labels:
    app-type: smesh-podmonitor
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/
    repoURL: https://github.com/glaceroy/httpbin-deploy.git
    targetRevision: HEAD
    helm:
      version: v3
      valuesFile:
        - helm/values.yaml
  info:
    - name: 'Purpose'
      value: 'Application to deploy smesh pod monitors'
  syncPolicy:
    automated: {}
